#!/bin/bash
#
#	/etc/rc.d/init.d/disable-offload
#
#	Disables network offload on ethernet devices.
#
# chkconfig: 2345 11 90
# description: Runs /usr/sbin/disable-offload to 
#              disable all NIC offload settings, such as
#              TSO, GRO, etc. 
#              This is a one-shot script, so
#              there's no daemon or pid file.

# Source function library.
. /etc/init.d/functions

start() {
	echo -n "Starting disable-offload: "
	# discard output since script logs errors
	/usr/sbin/disable-offload &> /dev/null
	_rc=$?
	[ $_rc -eq 0 ] && echo_success || echo_failure
	echo
	return $_rc
}	

stop() {
	echo -n "Shutting down disable-offload: "
	# nothing to do here
	echo_success
	echo
	return 0
}

status() {
        echo -n "Status of disable-offload: "
	/usr/sbin/disable-offload -V &> /dev/null
	_rc=$?
	[ $_rc -eq 0 ] && echo_success || echo_failure
	echo
	return $_rc
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: disable-offload {start|stop|status|restart}"
	exit 1
	;;
esac
exit $?
