#!/bin/bash

function usage() {
  cat >&2 <<- EOF
	Usage: $(basename $0) [-h] [-V]
	  -h help (this screen)
	  -V verify that offload is disabled on all NICs
	EOF
}

# tunables
offloads="rx tx sg tso ufo gso gro lro rxhash"
desired_state="off"
tag="disable_offload"

# defaults
change_settings=true
_rc=0

while getopts "Vh" option
do
  case $option in
    V ) change_settings=false;;
    h ) usage; exit 0;;
    * ) usage; exit 1;;
  esac
done

shift $(($OPTIND - 1))
#  Decrements the argument pointer so it points to next argument.
#  $1 now references the first non option item supplied on the command line
#  if one exists.
if [[ -n ${1} ]]; then
  usage
  exit 1
fi

for _num in {0..9}; do
  dev=eth${_num}
  ip link show $dev &> /dev/null || continue

  if [ $change_settings = "true" ]; then
    for offload in $offloads; do
      # this works for privileged user only (e.g. uid=0)
      ethtool -K $dev $offload $desired_state &> /dev/null
    done
  fi

  # check if we have bnx2x so we can skip the check for tx-checksumming
  # since we need a recent firmware in order to disable tx-checksumming
  # http://delivery04.dhe.ibm.com/sar/CMA/XSA/035pg/1/brcm_dd_nic_nx2-2.1.12c-1.70.40_rhel5_32-64.chg
  ethtool -i $dev 2> /dev/null | grep 'driver: bnx2x' &> /dev/null
  bnx2x=$?

  # check if we disabled everything (works for unpriv users)
  if [[ $bnx2x ]]; then
    _count=$(ethtool -k $dev 2> /dev/null | grep -v 'tx-checksumming' 2> /dev/null | grep '\bon\b' 2> /dev/null | wc -l)
  else
    _count=$(ethtool -k $dev 2> /dev/null | grep '\bon\b' 2> /dev/null | wc -l)
  fi
  if [ $_count -eq 0 ]; then
    _rc=0
  else
    logger -st $tag "error: one or more offload settings are still enabled"
    _rc=1
  fi
done

exit $_rc
